### ISSUE TITLE
NObject的Invocation跟XMPP的多博代理 MultiDelegate冲突

### ISSUE THREAD

**Issue by DreamBuddy** [jasenhuang/NSObjectSafe#12]
因为多博代理的Selector并没有人注册。。是nil

**Comment by jasenhuang** [comment]
@DreamBuddy  show the error ?

**Comment by DreamBuddy** [comment]
- (NSMethodSignature*)hookMethodSignatureForSelector:(SEL)aSelector {
    /* 如果 当前类有methodSignatureForSelector实现，NSObject的实现直接返回nil
     * 子类实现如下：
     *          NSMethodSignature* sig = [super methodSignatureForSelector:aSelector];
     *          if (!sig) {
     *              //当前类的methodSignatureForSelector实现
     *              //如果当前类的methodSignatureForSelector也返回nil
     *          }
     *          return sig;
     */
    NSMethodSignature* sig = [self hookMethodSignatureForSelector:aSelector];
    if (!sig){
        if (class_getMethodImplementation([NSObject class], @selector(methodSignatureForSelector:))
            != class_getMethodImplementation(self.class, @selector(methodSignatureForSelector:)) ){
            return nil;
        }
        return [NSMethodSignature signatureWithObjCTypes:"v@:@"];
    }
    return sig;
}

这个Hook方法不适用于XMPP的GCDMulticastDelegate

- (NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector
{
	for (GCDMulticastDelegateNode *node in delegateNodes)
	{
		id nodeDelegate = node.delegate;
		#if __has_feature(objc_arc_weak) && !TARGET_OS_IPHONE
		if (nodeDelegate == [NSNull null])
			nodeDelegate = node.unsafeDelegate;
		#endif
		
		NSMethodSignature *result = [nodeDelegate methodSignatureForSelector:aSelector];
		
		if (result != nil)
		{
			return result;
		}
	}
	
	// This causes a crash...
	// return [super methodSignatureForSelector:aSelector];
	
	// This also causes a crash...
	// return nil;
	
	return [[self class] instanceMethodSignatureForSelector:@selector(doNothing)];
}

GCDMulticastDelegate 动态转发了N条消息，但是没有一个属于self注册的方法。。所以上边您的那个判断就全部置为了nil ，继而重新创建了新的NSInvocation 但是丢失了argument 也就是传输的消息

**Comment by DreamBuddy** [comment]
(NSMethodSignature*)hookMethodSignatureForSelector:(SEL)aSelector {
/* 如果 当前类有methodSignatureForSelector实现，NSObject的实现直接返回nil
子类实现如下：
     
```NSMethodSignature* sig = [super methodSignatureForSelector:aSelector];
     if (!sig) {
         //当前类的methodSignatureForSelector实现
         //如果当前类的methodSignatureForSelector也返回nil
     }
     return sig;
/
NSMethodSignature sig = [self hookMethodSignatureForSelector:aSelector];
if (!sig){
if (class_getMethodImplementation([NSObject class], @selector(methodSignatureForSelector:))
!= class_getMethodImplementation(self.class, @selector(methodSignatureForSelector:)) ){
return nil;
}
return [NSMethodSignature signatureWithObjCTypes:"v@:@"];
}
return sig;
}
```
这个Hook方法不适用于XMPP的GCDMulticastDelegate


```(NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector
{
for (GCDMulticastDelegateNode *node in delegateNodes)
{
id nodeDelegate = node.delegate;
#if __has_feature(objc_arc_weak) && !TARGET_OS_IPHONE
if (nodeDelegate == [NSNull null])
nodeDelegate = node.unsafeDelegate;
#endif

  NSMethodSignature *result = [nodeDelegate methodSignatureForSelector:aSelector];
  
  if (result != nil)
  {
  	return result;
  }
}

// This causes a crash...
// return [super methodSignatureForSelector:aSelector];

// This also causes a crash...
// return nil;

return [[self class] instanceMethodSignatureForSelector:@selector(doNothing)];
}

```
GCDMulticastDelegate 动态转发了N条消息，但是没有一个属于self注册的方法。。所以上边您的那个判断就全部置为了nil ，继而重新创建了新的NSInvocation 但是丢失了argument 也就是传输的消息

**Comment by DreamBuddy** [comment]
```
(NSMethodSignature*)hookMethodSignatureForSelector:(SEL)aSelector {
/* 如果 当前类有methodSignatureForSelector实现，NSObject的实现直接返回nil
子类实现如下：
NSMethodSignature* sig = [super methodSignatureForSelector:aSelector];
     if (!sig) {
         //当前类的methodSignatureForSelector实现
         //如果当前类的methodSignatureForSelector也返回nil
     }
     return sig;
*/
NSMethodSignature sig = [self hookMethodSignatureForSelector:aSelector];
if (!sig){
    if (class_getMethodImplementation([NSObject class], @selector(methodSignatureForSelector:))
        != class_getMethodImplementation(self.class, @selector(methodSignatureForSelector:)) ){
        return nil;
    }
    return [NSMethodSignature signatureWithObjCTypes:"v@:@"];
    }
    return sig;
}
```
这个Hook方法不适用于XMPP的GCDMulticastDelegate


```(NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector
{
for (GCDMulticastDelegateNode *node in delegateNodes)
{
id nodeDelegate = node.delegate;
#if __has_feature(objc_arc_weak) && !TARGET_OS_IPHONE
if (nodeDelegate == [NSNull null])
nodeDelegate = node.unsafeDelegate;
#endif

  NSMethodSignature *result = [nodeDelegate methodSignatureForSelector:aSelector];
  
  if (result != nil)
  {
  	return result;
  }
}

// This causes a crash...
// return [super methodSignatureForSelector:aSelector];

// This also causes a crash...
// return nil;

return [[self class] instanceMethodSignatureForSelector:@selector(doNothing)];
}

```
GCDMulticastDelegate 动态转发了N条消息，但是没有一个属于self注册的方法。。所以上边您的那个判断就全部置为了nil ，继而重新创建了新的NSInvocation 但是丢失了argument 也就是传输的消息

**Comment by whihail** [comment]
@jasenhuang  @DreamBuddy 现在有解决方案吗？

**Comment by DreamBuddy** [comment]
@whihail 把NSObjectSafe里的那段代码注释掉 就行了...

**Comment by whihail** [comment]
@DreamBuddy  
```
- (void)hookForwardInvocation:(NSInvocation*)invocation
{
    NSString* info = [NSString stringWithFormat:@"unrecognized selector [%@] sent to %@", NSStringFromSelector(invocation.selector), NSStringFromClass(self.class)];
    [[NSNotificationCenter defaultCenter] postNotificationName:NSSafeNotification object:self userInfo:@{@"invocation":invocation}];
    [[NSSafeProxy new] dealException:info];
}
```
这一段要不要也注释掉

**Comment by whihail** [comment]
@DreamBuddy   并不会出现这个问题吧，multidelegate本身实现了这个方法，就不会去调用Object的这个方法，也就不会执行到)hookMethodSignatureForSelector:，所以你的情况应该是不存在的。

**Comment by jasenhuang** [comment]
@DreamBuddy
